// generated by unplugin-vue-components
// We suggest you to commit this file into source control
// Read more: https://github.com/vuejs/vue-next/pull/3399

declare module 'vue' {
  export interface GlobalComponents {
    AButton: typeof import('ant-design-vue/es')['Button']
    AConfigProvider: typeof import('ant-design-vue/es')['ConfigProvider']
    ATable: typeof import('ant-design-vue/es')['Table']
    EnProcess: typeof import('./components/EnProcess.md')['default']
    PageContent: typeof import('./components/page-content/src/page-content.vue')['default']
    TheFooter: typeof import('./components/TheFooter.vue')['default']
    ZhProcess: typeof import('./components/ZhProcess.md')['default']
  }
}

export { }
